# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    ls
  displayName: 'test'

# node.js is required to build Angular apps
- task: NodeTool@0
  inputs:
    versionSpec: '12.14'

# --dev option installs devDependencies from package.json
# probably needed for running the Karma tests
- script: |
    npm install --save-dev @angular-devkit/build-angular
    npm install -g @angular/cli
    npm install --dev
    ng build --prod
  displayName: 'npm install and build'

- script: |
    npx ng test --karma-config karma.conf.js --watch=false
  displayName: 'unit test'

